parameters:
#    ozeo_ozeo.example.class: Ozeo\OzeoBundle\Example

services:
#    ozeo_ozeo.example:
#        class: %ozeo_ozeo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
